
server:
  port: 9095

spring:
  application:
    name: CONFIG-SEVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Elyorbek-EED/online-school.git
          clone-on-start: true
          default-label: main


  profiles:
    active: native