server:
  port: 8081

spring:
  application:
    name: TEACHER-SERVICE

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30


management:
  endpoints:
    web:
      exposure:
        include: "*"
